version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     volumes:
        - my-db:/var/lib/mysql
     expose: 
        - '3306'
     ports:
        - '3800:3306'
     environment:
       MYSQL_ROOT_PASSWORD: rootPassword
       MYSQL_DATABASE: search-me
       MYSQL_USER: user
       MYSQL_PASSWORD: userPassowrd

volumes:
    my-db:
